[package]
name = "yassyui"
version = "0.1.0"
authors = ["poidl <hoitaus@gmail.com>"]
#workspace = "../.."

[dependencies]
libc = "*"
lv2 = { path = "../lv2" }
websocket = "*"

[lib]
name = "yassyui"
crate-type = ["rlib","dylib"] # ?
